version: 0.2
phases:
 install:
   runtime-versions:
     docker: 18
 pre_build:
   commands:
     - ws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 484349673031.dkr.ecr.eu-north-1.amazonaws.com/soduku-app
     - REPOSITORY_URI=484349673031.dkr.ecr.eu-north-1.amazonaws.com/soduku-app
     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
     - IMAGE_TAG=latest
 build:
   commands:
     - docker build -t $REPOSITORY_URI:latest -f Dockerfile .
     - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
 post_build:
   commands:
     - docker push $REPOSITORY_URI:latest
     - docker push $REPOSITORY_URI:$IMAGE_TAG
     - printf '[{"name":"nestjs-graphql","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
 files: imagedefinitions.json